// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwOu8Qp4taVEoXT_GBM1PMFSULmSF5iM',
    appId: '1:598331252747:web:0fd45455db205b76eea70e',
    messagingSenderId: '598331252747',
    projectId: 'ticketbookingsystem-169c7',
    authDomain: 'ticketbookingsystem-169c7.firebaseapp.com',
    storageBucket: 'ticketbookingsystem-169c7.appspot.com',
    measurementId: 'G-D9P7G590L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqH2je0c8yIffOCJ4LoeWELSCYBx_HZs',
    appId: '1:598331252747:android:ff0dc68e7236fb53eea70e',
    messagingSenderId: '598331252747',
    projectId: 'ticketbookingsystem-169c7',
    storageBucket: 'ticketbookingsystem-169c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbaPXOQNmKobZTPIjjK96JYwRHjt7LEXI',
    appId: '1:598331252747:ios:d5b0dddb28e63abbeea70e',
    messagingSenderId: '598331252747',
    projectId: 'ticketbookingsystem-169c7',
    storageBucket: 'ticketbookingsystem-169c7.appspot.com',
    iosClientId: '598331252747-9f1i8pahm556lgfs4lpm5ornhe6v42ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbaPXOQNmKobZTPIjjK96JYwRHjt7LEXI',
    appId: '1:598331252747:ios:d4f02c6f022b6070eea70e',
    messagingSenderId: '598331252747',
    projectId: 'ticketbookingsystem-169c7',
    storageBucket: 'ticketbookingsystem-169c7.appspot.com',
    iosClientId: '598331252747-oa7pfu1r96sadd88cc65gqucb7igal3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbs.RunnerTests',
  );
}
